# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-15 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[(b'Full Time', b'Full Time'), (b'Part Time', b'Part Time')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
