# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-15 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20200915_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='published_at',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, to='job.Category'),
        ),
    ]
